In [1]:
import numpy as np

In [2]:
# 1. Create an array A of size 5X5
A = np.random.randint(1, 100, (5, 5))

In [3]:
# 1a. Shape of the array
shape_of_A = A.shape

In [10]:
shape_of_A

(5, 5)

In [5]:
# 1b. Length of each element of the array in Bytes
element_size_bytes = A.itemsize

In [11]:
element_size_bytes

8

In [7]:
# 1c. Array of elements in the second column of each row
second_column = A[:, 1]

In [12]:
second_column

array([61, 48,  3, 55, 61])

In [8]:
# 1d. Create a new array S having the square of each item of the created array A
S = np.square(A)

In [9]:
# 1e. Print the array elements in the reverse order
reversed_A = A.flatten()[::-1]

In [13]:
reversed_A

array([ 7, 25, 88, 61, 34, 68, 84, 52, 55, 80, 75, 47,  4,  3,  6, 41, 14,
       74, 48, 18, 12, 66,  8, 61, 51])

In [14]:
# 2. Create a 10x10 array with random values and find the minimum and maximum values.
B = np.random.random((10, 10))

In [15]:
min_value_B = B.min()

In [17]:
min_value_B

np.float64(0.007885061761525924)

In [18]:
max_value_B = B.max()

In [19]:
max_value_B

np.float64(0.9960507069253938)

In [24]:
# 3. Create two random arrays A and B, check if they are equal.
A_random = np.random.randint(1, 100, (5, 5))

In [25]:
B_random = np.random.randint(1, 100, (5, 5))

In [26]:
arrays_equal = np.array_equal(A_random, B_random)

In [27]:
arrays_equal

False

In [28]:
# 4. Define matrix_operations function

In [30]:
def matrix_operations(A, B):
    # 1. Compute the element-wise sum of A and B
    elementwise_sum = np.add(A, B)
    
    # 2. Compute the element-wise product of A and B
    elementwise_product = np.multiply(A, B)
    
    # 3. Compute the dot product of A and B
    dot_product = np.dot(A, B)
    
    # 4. Compute the transpose of the resulting dot product matrix
    transpose_dot_product = np.transpose(dot_product)
    
    return elementwise_sum, elementwise_product, dot_product, transpose_dot_product


In [31]:
# Create two sample matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [32]:
# Call the matrix_operations function
elementwise_sum, elementwise_product, dot_product, transpose_dot_product = matrix_operations(A, B)

In [33]:
elementwise_sum

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [34]:
elementwise_product

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [35]:
dot_product

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [36]:
transpose_dot_product

array([[ 30,  84, 138],
       [ 24,  69, 114],
       [ 18,  54,  90]])

In [37]:
def solve_linear_system(A, b):
    try:
        # Solve for x in Ax = b
        x = np.linalg.solve(A, b)
        return x
    except np.linalg.LinAlgError:
        return "The system has no unique solution."

In [38]:
# Create a sample matrix A and vector b
A = np.array([[3, 1, -1],
              [2, 4, 1],
              [-1, 2, 5]])

b = np.array([4, 1, 1])


In [39]:
# Solve the linear system
x = solve_linear_system(A, b)